### PR TITLE
Support utf8 characters in qrcode and decode qrcode image test

### PR DESCRIPTION
**Pull request by fukata**
I have been using labelmake.jp very conveniently.

This time, I wanted to support Chinese and Thai for QR code values, so I did. I have also added a test to see if the input values are stored by parsing the actual generated QR code image.

What I don't fully understand

Originally, I think there was garbled text in the case of multiple hiragana characters.

This time, I reverted to the previous implementation that did not convert to SJIS, but I could not confirm the garbled characters in the unit test run.

I wonder if the cause of the garbled text was not in the library but in the execution environment.

If there is a way to reproduce the problem here, please let me know so I can try.

------

Japanese

labelmake.jp を便利に使わせていただいております。

今回、QRコードの値に中国語、タイ語も対応したかったので対応しました。また、実際に生成されたQRコードの画像をパースして入力値が格納されているかのテストも追加しています。

理解しきれていない点

元々、複数のひらがなの場合にも文字化けしていたかと思います。

今回、SJISに変換しない前の実装に戻す形になりましたがユニットテストの実行では文字化けは確認できませんでした。

元々文字化けしていた原因というのはライブラリではなく実行環境側に何か原因があったのでしょうか？

もし、こちら側で再現が可能な方法があれば試してみますので教えて下さい。

### CODE REVIEW

**Comment by hand-dot** [comment]
Hi @fukata !

First of all thank you, I am very grad with the PR.

The unit test using jsQR is pretty cool!

I'm also wondering why encoding-japanese is not necessary...
It's hard for me to understand because I used to get garbled characters when reading QRcode containing Kanji and Hiragana.

Was the version of bwip-js in my local node_modules too old?
Anyway, I'll test it here too.
If there is no problem, encoding-japanese will be unnecessary and I will approve this PR.

---

A minor point...
`backgroundcolor` should be `backgroundColor`
It's subtle, but I'd like it to be consistent with the following
https://github.com/hand-dot/labelmake/blob/b4c16aaef4361936e0eaed4ca7d7d8a59aa5c776/src/type.ts#L33

Thanks.

**Comment by hand-dot** [comment]
- [ ] Test at hand-dot's local environment

**Comment by fukata** [comment]
Thank you!

If you need any additional verification, please let me know and I will test it here as well.

**Comment by hand-dot** [comment]
@fukata 
Some QR code reader application was not analyzing the data properly.

I used "QR & Barcode Reader" app, the hiragana characters were garbled.
https://play.google.com/store/apps/details?id=com.teacapps.barcodescanner&hl=en&gl=US
```
あいうえおあいうえお -> Garbled
漢字も有効です。 -> OK
新年快乐 -> OK
สวัสดีปีใหม่ -> OK
```
But, when I used "QRQR - QR Code® Reader" app, all the characters were read correctly.
https://play.google.com/store/apps/details?id=com.arara.q&hl=en&gl=US

---

I found out that if I use `encoding-japanese`, I can read the QR Code with "QR & Barcode Reader" without any garbled characters.

The character code of QR code is Shift_JIS, but if the reader converts it to Shift_JIS, it can be read correctly, but if it does not, garbled characters will occur.

Therefore, `encoding-japanese` is able to avoid the problem of being readable or unreadable depending on the QR Code reader.

I like this PR fix for automatic testing of QR codes😄 
I will import it into develop once and implement the rest on my own.

Thanks!

**Comment by fukata** [comment]
> The character code of QR code is Shift_JIS, but if the reader converts it to Shift_JIS, it can be read correctly, but if it does not, garbled characters will occur.

I did not know the encoding specifications of the QR Code itself. Thank you very much.

**Pull request merged**
