### PR TITLE
Split (word-wrap) overfull lines on previous whitespace

### PR DESCRIPTION
**Pull request by tilman**
I changed the code of the `getSplit` function to split the lines which are too long on the gap between two words. The previous implementation was splitting the lines in the middle of a word. 
Also i refactored a bit of the code around getSplit and moved it into the already existing `util.ts` to make it a bit more readable. 

Hope this helps! If you have any more ideas just let me know :)

### CODE REVIEW

**Comment by hand-dot** [comment]
@tilman 
wow. I’ll review these changes.

I’d like to see that how did it change.
If you can, please tell me how to reenact by screen capture or template data or something.

Thanks a lot!

**Comment by tilman** [comment]
Hey, sure. I just made two pictures:
This was before my update:
pdf_before

And this was after my update:
pdf_corrected

**Comment by tilman** [comment]
Also i added splitThreshold as config option in case someone want to change the threshold by itself.

**Comment by tilman** [comment]
Hey @hand-dot do you think anything else is missing or could we merge this PR? Let me know if you think this needs some further improvements

**Comment by hand-dot** [comment]
@tilman 
Sorry for the late reply.
I was checking the previews on the following sites to make sure they were compatible.
https://labelmake.jp/javascript-pdf-generator-library/template-design/

Is this modification equal to `word-break: break-word;`?

**Comment by tilman** [comment]
Jep, It's having the same behaviour as break-word. Normally a line breaks on spaces, if a very long word is longer as a line we break in the middle of the word.

**Comment by hand-dot** [comment]
@tilman 
Thanks! I'll merge and release it as a new version!

**Comment by hand-dot** [comment]
Released labelmake@2.0.18 !!

**Comment by tilman** [comment]
Great! Thanks a lot :)

**Pull request merged**
